[workspace]
resolver= "2"

members = [
    "core",
    "wallet",
    "mint"
]

[profile.dev]
split-debuginfo = "unpacked"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
lto = true # Enable link-time optimization.

[workspace.metadata]
authors = ["The cashu-rs Developers"]
edition = "2021"
description = "cashu-rs"
readme = "README.md"
repository = "https://github.com/ngutech21/cashu-rs"
license-file = "LICENSE"
keywords = ["bitcoin", "e-cash"]