[workspace]
resolver= "2"

members = [
    "moksha-core",
    "moksha-wallet",
    "moksha-mint",
    "flutter/native",
    "integrationtests"
]

[profile.dev]
split-debuginfo = "unpacked"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
lto = true # Enable link-time optimization.

[workspace.metadata]
authors = ["The moksha Developers"]
edition = "2021"
description = "moksha is a cashu wallet and mint"
readme = "README.md"
repository = "https://github.com/ngutech21/cashu-rs"
license-file = "LICENSE"
keywords = ["bitcoin", "e-cash"]