[workspace]

members = [
    "core",
    "wallet",
    "mint"
]

[workspace.metadata]
authors = ["The cashu-rs Developers"]
edition = "2021"
description = "cashu-rs"
readme = "README.md"
repository = "https://github.com/ngutech21/cashu-rs"
license-file = "LICENSE"
keywords = ["bitcoin", "e-cash"]