[package]
name = "cashurs-wallet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
anyhow = {version="1.0.71", features = ["backtrace"] }
clap = { version = "4.2.7", features = ["derive"] }
dotenvy = "0.15.7"
reqwest = {version= "0.11.17", features = ["serde_json","json"]}
secp256k1 = {version="0.27.0", features = [ "serde" ]}
tokio = { version = "1.28.0", features = ["full"] }
cashurs-core = { path = "../core" }
serde_json = "1.0.96"
serde = "1.0.162"
rand = "0.8.5"
thiserror = "1.0.40"
async-trait = "0.1.68"
mockall = "0.11.4"
rocksdb = "0.20.1"
lightning-invoice = "0.23.0"


[dev-dependencies]