[package]
name = "cashurs-wallet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
anyhow = "1.0.70"
clap = { version = "4.2.4", features = ["derive"] }
dotenvy = "0.15.7"
reqwest = {version= "0.11.16", features = ["serde_json","json"]}
secp256k1 = {version="0.27.0", features = [ "serde" ]}
tokio = { version = "1.27.0", features = ["full"] }
cashurs-core = { path = "../core" }
serde_json = "1.0.96"
