[package]
name = "moksha-fedimint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "moksha_fedimint"
path = "src/lib.rs"

[dependencies]
base64 = "0.20.0"
anyhow = { version = "1.0.71", features = ["backtrace"] }
tokio = { version = "1.28.2", features = ["full"] }
serde_json = "1.0.96"
dirs = "5.0.1"
futures = "0.3.28"
lightning-invoice = { version = "0.21.0", features = ["serde"] }
fedimint-sqlite = { git = "https://github.com/fedimint/fedimint", rev = "b5a1d8db7e3b8eb83fedc202c6410e6af60de12b" }
fedimint-client = { git = "https://github.com/fedimint/fedimint", rev = "b5a1d8db7e3b8eb83fedc202c6410e6af60de12b" }
fedimint-core = { git = "https://github.com/fedimint/fedimint", rev = "b5a1d8db7e3b8eb83fedc202c6410e6af60de12b" }
fedimint-mint-client = { git = "https://github.com/fedimint/fedimint", rev = "b5a1d8db7e3b8eb83fedc202c6410e6af60de12b" }
fedimint-ln-client = { git = "https://github.com/fedimint/fedimint", rev = "b5a1d8db7e3b8eb83fedc202c6410e6af60de12b" }
fedimint-wallet-client = { git = "https://github.com/fedimint/fedimint", rev = "b5a1d8db7e3b8eb83fedc202c6410e6af60de12b" }
moksha-core = { path = "../moksha-core" }
