[package]
name = "native"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
moksha-wallet = { path = "../../moksha-wallet" }
moksha-core = { path = "../../moksha-core" }
moksha-fedimint = { path = "../../moksha-fedimint" }

anyhow = { version = "1.0.72", features = ["backtrace"] }
thiserror = "1.0.44"
flutter_rust_bridge = "1.79.0"
lazy_static = "1.4.0"
tokio = { version = "1.29.1", features = ["rt", "sync"] }
lightning-invoice = "0.23.0"
async-trait = "0.1.72"
url = "2.4.0"
secp256k1 = { version = "0.27.0", features = ["rand", "serde"] }

[target.'cfg(target_family="wasm")'.dependencies]
gloo-net = "0.3.1"
serde = "1.0.178"
serde_json = "1.0.104"

[target.'cfg(not(target_family="wasm"))'.dependencies]
reqwest = { version = "0.11.18", features = ["serde_json", "json", "rustls-tls"], default-features = false }

[dev-dependencies]
tempfile = "3.6.0"
