[package]
name = "moksha-core"
version = "0.1.1"
edition = "2021"
repository = "https://github.com/ngutech21/moksha"
license = "MIT"
description = "A library for building cashu applications"

[lib]
name = "moksha_core"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.75"
url = "2.4.1"
base64 = "0.21.2"
bitcoin_hashes = "0.12.0"
rand = "0.8.5"
secp256k1 = { version = "0.27.0", features = ["rand", "serde"] }
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
hex = "0.4.3"
serde_with = "3.4.0"
thiserror = "1.0.49"
itertools = "0.11.0"

[target.'cfg(target_family = "wasm")'.dependencies]
# getrandom is transitive dependency of rand
# on wasm, we need to enable the js backend
# see https://docs.rs/getrandom/latest/getrandom/#indirect-dependencies and https://docs.rs/getrandom/latest/getrandom/#webassembly-support
getrandom = { version = "0.2.8", features = ["js"] }

[dev-dependencies]
anyhow = "1.0.75"
