[package]
name = "moksha-mint"
version = "0.1.2"
edition = "2021"
repository = "https://github.com/ngutech21/moksha"
license = "MIT"
description = "A cashu-mint written in Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "moksha-mint"
path = "src/bin/moksha-mint.rs"

[lib]
name = "mokshamint"
path = "src/lib.rs"

[dependencies]
hex = "0.4.3"
async-trait = "0.1.74"
bitcoin_hashes = "0.12.0"
anyhow = { version = "1.0.75", features = ["backtrace"] }
axum = { version = "0.7.2", features = ["http2"] }

hyper = "0.14.27"
serde = { version = "1.0.193", features = ["derive"] }
serde_derive = "1.0.171"
serde_json = "1.0.108"
serde_with = "3.4.0"
tokio = { version = "1.34.0", features = ["full"] }
tower-http = { version = "0.5.0", features = ["trace", "cors", "fs", "set-header"] }
tower-service = { version = "0.3.2" }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
secp256k1 = { version = "0.28.0", features = ["rand", "serde"] }
thiserror = "1.0.50"
moksha-core = { path = "../moksha-core", version = "0.1.2" }
rocksdb = "0.21.0"
lightning-invoice = "0.26.0"
reqwest = { version = "0.11.22", default-features = false, features = ["serde_json", "json", "rustls-tls", "socks"] }
url = "2.4.1"
dotenvy = "0.15.7"
envy = "0.4.2"
fedimint-tonic-lnd = { version = "0.1.3", features = ["lightningrpc"] }
uuid = { version = "1.6.1", features = ["serde", "v4"] }

[dev-dependencies]
tempfile = "3.8.1"
tower = { version = "0.4", features = ["util"] }
mockall = "0.11.4"
hex = "0.4.3"
http-body-util = "0.1.0"
