name: docker-push-dockerhub

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to docker.io
        uses: docker/login-action@v2.1.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: docker.io/${{ secrets.DOCKER_NAME }}/moksha-mint:latest
