name: flutter

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.16.0
          channel: "stable"
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - working-directory: "flutter"
        run: flutter build linux
