name: flutter

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  main:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter SDK
        uses: mobiledevops/flutter-sdk-action@v1.0.0
        with:
          flutter-sdk-version: 3.10.4
      - working-directory: "flutter"
        run: flutter build macos
