name: flutter

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  main:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.13.1
          channel: "stable"
          architecture: x64
      - working-directory: "flutter"
        run: flutter build macos
